POST http://localhost:8080/api/1.0/login
Content-Type: application/json

{
  "username": "taleh",
  "password": "<>"
}
###
POST http://localhost:8080/register
Content-Type: application/json

{
  "username": "taleh",
  "password": "<>",
  "fullName": "Taleh Ibrahimli"
}
