GET http://localhost:8080/api/1.0/models?name=imdb/artist
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0YWxlaCIsImV4cCI6MTYwMTQ5NDEzNn0.RXj5os-isjMpA5MigtCSfdxMa0XoHfXV4keyX-m2mivc0t-we9O6Fv0fy9SXzgvigHu4VoIC_hE5ac17Q58p1w

###
PUT http://localhost:8080/api/1.0/models?name=imdb/artist
Content-Type: application/json

{
  "examples": [
    {
      "id": 1,
      "url": "https://www.imdb.com/name/nm1720028/?ref_=tt_cl_t1"
    },
    {
      "id": 2,
      "url": "https://www.imdb.com/name/nm1869101/?ref_=nv_sr_srsg_0"
    },
    {
      "id": 3,
      "url": "https://www.imdb.com/name/nm0000115/?ref_=nv_sr_srsg_0"
    }
  ],
  "markers": [
    {
      "name": "marker-13",
      "type": "meta-data",
      "parentName": null,
      "parameters": {
        "meta-tags": true
      }
    },
    {
      "name": "marker-12",
      "type": "text-transform",
      "parentName": null,
      "parameters": {
        "output-select": "ug-value",
        "substitution": "",
        "transformer": "REGEX_REPLACE",
        "output-type": "ATTR",
        "input-type": "TEXT",
        "script": "[\\(\\)]",
        "element": "#knownfor > .knownfor-title > .knownfor-year"
      }
    },
    {
      "name": "marker-11",
      "type": "field-selector",
      "parentName": null,
      "parameters": {
        "name": "name",
        "selector": "#name-overview-widget-layout > tbody > tr:nth-child(1) > td.name-overview-widget__section > h1.header > span.itemprop"
      }
    },
    {
      "name": "marker-1",
      "type": "field-selector",
      "parentName": null,
      "parameters": {
        "name": "bio",
        "selector": "#name-bio-text > div.name-trivia-bio-text > div.inline"
      }
    },
    {
      "name": "marker-3",
      "type": "field-selector",
      "parentName": null,
      "parameters": {
        "name": "specialities",
        "selector": "#name-job-categories > a > span.itemprop"
      }
    },
    {
      "name": "marker-4",
      "type": "field-selector",
      "parentName": null,
      "parameters": {
        "name": "knownFor",
        "selector": "#knownfor > .knownfor-title"
      }
    },
    {
      "name": "marker-5",
      "type": "field-selector",
      "parentName": null,
      "parameters": {
        "name": "year",
        "selector": "#knownfor > .knownfor-title > .knownfor-year"
      }
    },
    {
      "name": "marker-7",
      "type": "field-selector",
      "parentName": null,
      "parameters": {
        "name": "character",
        "selector": "#knownfor > .knownfor-title > .knownfor-title-role > span"
      }
    },
    {
      "name": "marker-6",
      "type": "field-selector",
      "parentName": null,
      "parameters": {
        "name": "title",
        "selector": "#knownfor > .knownfor-title > .knownfor-title-role > a"
      }
    },
    {
      "name": "marker-8",
      "type": "field-selector",
      "parentName": null,
      "parameters": {
        "name": "namePoster",
        "selector": "#name-poster"
      }
    },
    {
      "name": "marker-9",
      "type": "field-selector",
      "parentName": null,
      "parameters": {
        "name": "bornDate",
        "selector": "#name-born-info > time"
      }
    },
    {
      "name": "marker-10",
      "type": "field-selector",
      "parentName": null,
      "parameters": {
        "name": "bornPlace",
        "selector": "#name-born-info > a"
      }
    },
    {
      "name": "marker-14",
      "type": "field-selector",
      "parentName": null,
      "parameters": {
        "name": "consMeter",
        "selector": "#meterRank"
      }
    },
    {
      "name": "marker-15",
      "type": "field-selector",
      "parentName": null,
      "parameters": {
        "name": "awards",
        "selector": "#maindetails_center_bottom > div.article.highlighted > span.awards-blurb"
      }
    },
    {
      "name": "marker-16",
      "type": "element-to-element-transform",
      "parentName": null,
      "parameters": {
        "child_selector": ".filmo-category-section",
        "parent_selector": "#filmography > div.head > a",
        "parent_attr": "catname"
      }
    },
    {
      "name": "marker-17",
      "type": "field-selector",
      "parentName": null,
      "parameters": {
        "name": "cast",
        "selector": "#filmography > div.filmo-category-section[catname=Actress] > div.filmo-row,#filmography > div.filmo-category-section[catname=Actor] > div.filmo-row"
      }
    },
    {
      "name": "marker-18",
      "type": "field-selector",
      "parentName": null,
      "parameters": {
        "name": "movieName",
        "selector": "#filmography > div.filmo-category-section[catname=Actress] > div.filmo-row > b > a,#filmography > div.filmo-category-section[catname=Actor] > div.filmo-row > b > a"
      }
    },
    {
      "name": "marker-19",
      "type": "field-selector",
      "parentName": null,
      "parameters": {
        "name": "movieStatus",
        "selector": "#filmography > div.filmo-category-section[catname=Actress] > div.filmo-row > a.in_production,#filmography > div.filmo-category-section[catname=Actor] > div.filmo-row > a.in_production"
      }
    },
    {
      "name": "marker-20",
      "type": "text-wrap",
      "parentName": null,
      "parameters": {
        "element": "#filmography > div.filmo-category-section > div.filmo-row"
      }
    },
    {
      "name": "marker-21",
      "type": "field-selector",
      "parentName": null,
      "parameters": {
        "name": "character",
        "selector": "#filmography > div.filmo-category-section[catname=Actress] > div.filmo-row > text:last-child,#filmography > div.filmo-category-section[catname=Actor] > div.filmo-row > text:last-child"
      }
    },
    {
      "name": "marker-22",
      "type": "field-selector",
      "parentName": null,
      "parameters": {
        "name": "year",
        "selector": "#filmography > div.filmo-category-section[catname=Actress] > div.filmo-row > span.year_column,#filmography > div.filmo-category-section[catname=Actor] > div.filmo-row > span.year_column"
      }
    }
  ]
}
